pipeline {
    agent any

    stages {
        stage('Checkout playbook') {
            steps {
                git branch: 'master',
                url: 'https://github.com/zayanimal/playbooks.git'
            }
        }

        stage('Run playbook') {
            steps {
                ansiColor('xterm') {
                    ansiblePlaybook playbook: 'tapetown-update.yml', inventory: '/var/local/ansible/hosts.ini', credentialsId: 'tapetown_cred-ssh'
                }
            }
        }
    }
}